### PR TITLE
Merge pull request #1 from bosunolanrewaju/master

### PR DESCRIPTION
**Pull request by temiadesina**
Merge Changes

### CODE REVIEW

**Comment by temiadesina** [comment]
Gonna Push

**Comment by bosunolanrewaju** [comment]
@temiadesina what are you trying to merge to master?

**Comment by temiadesina** [comment]
Sorry this is  mistake it said I was two commits behind so I wanted to pull
from your master

**Comment by bosunolanrewaju** [comment]
Oh okay. I'm closing it then

**Pull request closed without merging**
